//! Built-in theme definitions embedded via `include_str!` at compile time.
//!
//! The JSON sources live in `crates/titi-tui/themes/` (dark + light) and
//! `crates/titi-tui/themes/defaults/` (the 98 default themes). They mirror
//! the omp `packages/coding-agent/src/modes/theme/` theme registry.

/// Built-in themes: (name, JSON content).
pub static BUILTIN_THEMES: &[(&str, &str)] = &[
    ("dark", include_str!("../../themes/dark.json")),
    ("light", include_str!("../../themes/light.json")),
    ("alabaster", include_str!("../../themes/defaults/alabaster.json")),
    ("amethyst", include_str!("../../themes/defaults/amethyst.json")),
    ("anthracite", include_str!("../../themes/defaults/anthracite.json")),
    ("basalt", include_str!("../../themes/defaults/basalt.json")),
    ("birch", include_str!("../../themes/defaults/birch.json")),
    ("dark-abyss", include_str!("../../themes/defaults/dark-abyss.json")),
    ("dark-arctic", include_str!("../../themes/defaults/dark-arctic.json")),
    ("dark-aurora", include_str!("../../themes/defaults/dark-aurora.json")),
    ("dark-catppuccin", include_str!("../../themes/defaults/dark-catppuccin.json")),
    ("dark-cavern", include_str!("../../themes/defaults/dark-cavern.json")),
    ("dark-copper", include_str!("../../themes/defaults/dark-copper.json")),
    ("dark-cosmos", include_str!("../../themes/defaults/dark-cosmos.json")),
    ("dark-cyberpunk", include_str!("../../themes/defaults/dark-cyberpunk.json")),
    ("dark-dracula", include_str!("../../themes/defaults/dark-dracula.json")),
    ("dark-eclipse", include_str!("../../themes/defaults/dark-eclipse.json")),
    ("dark-ember", include_str!("../../themes/defaults/dark-ember.json")),
    ("dark-equinox", include_str!("../../themes/defaults/dark-equinox.json")),
    ("dark-forest", include_str!("../../themes/defaults/dark-forest.json")),
    ("dark-github", include_str!("../../themes/defaults/dark-github.json")),
    ("dark-gruvbox", include_str!("../../themes/defaults/dark-gruvbox.json")),
    ("dark-lavender", include_str!("../../themes/defaults/dark-lavender.json")),
    ("dark-lunar", include_str!("../../themes/defaults/dark-lunar.json")),
    ("dark-midnight", include_str!("../../themes/defaults/dark-midnight.json")),
    ("dark-monochrome", include_str!("../../themes/defaults/dark-monochrome.json")),
    ("dark-monokai", include_str!("../../themes/defaults/dark-monokai.json")),
    ("dark-nebula", include_str!("../../themes/defaults/dark-nebula.json")),
    ("dark-nord", include_str!("../../themes/defaults/dark-nord.json")),
    ("dark-ocean", include_str!("../../themes/defaults/dark-ocean.json")),
    ("dark-one", include_str!("../../themes/defaults/dark-one.json")),
    ("dark-poimandres", include_str!("../../themes/defaults/dark-poimandres.json")),
    ("dark-rainforest", include_str!("../../themes/defaults/dark-rainforest.json")),
    ("dark-reef", include_str!("../../themes/defaults/dark-reef.json")),
    ("dark-retro", include_str!("../../themes/defaults/dark-retro.json")),
    ("dark-rose-pine", include_str!("../../themes/defaults/dark-rose-pine.json")),
    ("dark-sakura", include_str!("../../themes/defaults/dark-sakura.json")),
    ("dark-slate", include_str!("../../themes/defaults/dark-slate.json")),
    ("dark-solarized", include_str!("../../themes/defaults/dark-solarized.json")),
    ("dark-solstice", include_str!("../../themes/defaults/dark-solstice.json")),
    ("dark-starfall", include_str!("../../themes/defaults/dark-starfall.json")),
    ("dark-sunset", include_str!("../../themes/defaults/dark-sunset.json")),
    ("dark-swamp", include_str!("../../themes/defaults/dark-swamp.json")),
    ("dark-synthwave", include_str!("../../themes/defaults/dark-synthwave.json")),
    ("dark-taiga", include_str!("../../themes/defaults/dark-taiga.json")),
    ("dark-terminal", include_str!("../../themes/defaults/dark-terminal.json")),
    ("dark-tokyo-night", include_str!("../../themes/defaults/dark-tokyo-night.json")),
    ("dark-tundra", include_str!("../../themes/defaults/dark-tundra.json")),
    ("dark-twilight", include_str!("../../themes/defaults/dark-twilight.json")),
    ("dark-volcanic", include_str!("../../themes/defaults/dark-volcanic.json")),
    ("graphite", include_str!("../../themes/defaults/graphite.json")),
    ("light-arctic", include_str!("../../themes/defaults/light-arctic.json")),
    ("light-aurora-day", include_str!("../../themes/defaults/light-aurora-day.json")),
    ("light-canyon", include_str!("../../themes/defaults/light-canyon.json")),
    ("light-catppuccin", include_str!("../../themes/defaults/light-catppuccin.json")),
    ("light-cirrus", include_str!("../../themes/defaults/light-cirrus.json")),
    ("light-coral", include_str!("../../themes/defaults/light-coral.json")),
    ("light-cyberpunk", include_str!("../../themes/defaults/light-cyberpunk.json")),
    ("light-dawn", include_str!("../../themes/defaults/light-dawn.json")),
    ("light-dunes", include_str!("../../themes/defaults/light-dunes.json")),
    ("light-eucalyptus", include_str!("../../themes/defaults/light-eucalyptus.json")),
    ("light-forest", include_str!("../../themes/defaults/light-forest.json")),
    ("light-frost", include_str!("../../themes/defaults/light-frost.json")),
    ("light-github", include_str!("../../themes/defaults/light-github.json")),
    ("light-glacier", include_str!("../../themes/defaults/light-glacier.json")),
    ("light-gruvbox", include_str!("../../themes/defaults/light-gruvbox.json")),
    ("light-haze", include_str!("../../themes/defaults/light-haze.json")),
    ("light-honeycomb", include_str!("../../themes/defaults/light-honeycomb.json")),
    ("light-lagoon", include_str!("../../themes/defaults/light-lagoon.json")),
    ("light-lavender", include_str!("../../themes/defaults/light-lavender.json")),
    ("light-meadow", include_str!("../../themes/defaults/light-meadow.json")),
    ("light-mint", include_str!("../../themes/defaults/light-mint.json")),
    ("light-monochrome", include_str!("../../themes/defaults/light-monochrome.json")),
    ("light-ocean", include_str!("../../themes/defaults/light-ocean.json")),
    ("light-one", include_str!("../../themes/defaults/light-one.json")),
    ("light-opal", include_str!("../../themes/defaults/light-opal.json")),
    ("light-orchard", include_str!("../../themes/defaults/light-orchard.json")),
    ("light-paper", include_str!("../../themes/defaults/light-paper.json")),
    ("light-poimandres", include_str!("../../themes/defaults/light-poimandres.json")),
    ("light-prism", include_str!("../../themes/defaults/light-prism.json")),
    ("light-retro", include_str!("../../themes/defaults/light-retro.json")),
    ("light-sand", include_str!("../../themes/defaults/light-sand.json")),
    ("light-savanna", include_str!("../../themes/defaults/light-savanna.json")),
    ("light-solarized", include_str!("../../themes/defaults/light-solarized.json")),
    ("light-soleil", include_str!("../../themes/defaults/light-soleil.json")),
    ("light-sunset", include_str!("../../themes/defaults/light-sunset.json")),
    ("light-synthwave", include_str!("../../themes/defaults/light-synthwave.json")),
    ("light-tokyo-night", include_str!("../../themes/defaults/light-tokyo-night.json")),
    ("light-wetland", include_str!("../../themes/defaults/light-wetland.json")),
    ("light-zenith", include_str!("../../themes/defaults/light-zenith.json")),
    ("limestone", include_str!("../../themes/defaults/limestone.json")),
    ("mahogany", include_str!("../../themes/defaults/mahogany.json")),
    ("marble", include_str!("../../themes/defaults/marble.json")),
    ("obsidian", include_str!("../../themes/defaults/obsidian.json")),
    ("onyx", include_str!("../../themes/defaults/onyx.json")),
    ("pearl", include_str!("../../themes/defaults/pearl.json")),
    ("porcelain", include_str!("../../themes/defaults/porcelain.json")),
    ("quartz", include_str!("../../themes/defaults/quartz.json")),
    ("sandstone", include_str!("../../themes/defaults/sandstone.json")),
    ("titanium", include_str!("../../themes/defaults/titanium.json")),
];

/// Get a built-in theme by name.
pub fn get_builtin_theme(name: &str) -> Option<&'static str> {
    BUILTIN_THEMES.iter().find(|(n, _)| *n == name).map(|(_, c)| *c)
}

/// List all built-in theme names.
pub fn list_builtin_themes() -> Vec<&'static str> {
    BUILTIN_THEMES.iter().map(|(n, _)| *n).collect()
}
